### ISSUE TITLE
1st level regeneration pill issue

### ISSUE THREAD

**Issue by dhubber** [dhubber/PillsGame#42]
On 2 occasions, by chance the very first pill I took was the level regeneration pill.  I noticed (i) on the first occasion there was only 1 pill in the new level when there should have been 2 remaining, and (ii) on both occasions none of the remaining pills were the death pill.  I'm guessing both of these are bugs.  I thought the regeneration guarantees both the number and types of pills or am I wrong?

**Comment by Sebeb** [comment]
Yeah, it should just move all the remaining pills around, will look into it!

**Comment by Sebeb** [comment]
Hmm I haven't been able to recreate this bug somehow. Could it be that it accidentally fixed itself in the latest version?

**Comment by dhubber** [comment]
Okay, just tried with the DevMenu on level 1 and there's no Death Pill again.  However, I don't know how the DevMenu works with this since we're not actually eating a pill in the level in that case.  I'll keep trying to reproduce it though.

**Comment by Sebeb** [comment]
It is currently the case that it's possible for the maze to regen a pill directly on the player, forcing the player to take it. Since regenerating the maze also grants invincibility, I think the death pill would have no noticeable effect. There's a chance this happened? You can force a pill to spawn in levels by replacing the death pill in the pill manager with the pill you want to force to spawn, and then adding all the levels you want it to appear in in the death pill spawns list.

**Comment by Sebeb** [comment]
I think this one's gone, but please reopen if it appears again.
